force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{YYYY}-{MM}-{000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ApplicationContactUtils.cls
public with sharing class ApplicationContactUtils {
    public static void setPrimaryContacts (List<Application_Contact__c> appContacts){
        Map<Id, Application_Contact__c> appIdsByContact = new Map<Id, Application_Contact__c>();
        List<Job_Application__c> appsToUpdate = new List<Job_Application__c>();

        for (Application_Contact__c con : appContacts){
            appIdsByContact.put(con.Job_Application__c, con);
        }

        List<Job_Application__c> apps = [SELECT Id, Name FROM Job_Application__c WHERE Id IN :appIdsByContact.keySet()];

        for (Job_Application__c app : apps) {
            if (app.Primary_Contact__c == null){
                app.Primary_Contact__c = appIdsByContact.get(app.Id).Id;
                appsToUpdate.add(app);
            }
        }
        update appsToUpdate;
    }
}